version: 1.0.0.{build}
image: Visual Studio 2017

before_build:
  - nuget restore OneSignal.RestAPIv3.Client.sln

build:
  project: OneSignal.RestAPIv3.Client.sln
  parallel: true
  verbosity: minimal

artifacts:
  - path: C:\projects\onesignal-restapiv3-client\OneSignal.RestAPIv3.Client\bin\Release\*.nupkg
configuration: Release

test: off
